# Change these first
owner: immoreel # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: COA
    url: https://www.coa.nl/nl
  - name: Kamp Woudenberg
    url: https://www.kampwoudenberg.nl  
  - name: The Good Hairclub
    url: https://thegoodhairclub.nl 
  - name: PKN Ontmoetingskerk Wilnis
    url: https://pknontmoetingskerkwilnis.nl
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain.
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Get up, get down!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
